import sys
from PyQt5.QtWidgets import QApplication,QMainWindow
import os
from PyQt5 import QtCore, QtGui, QtWidgets
import csv
import numpy as np
from scipy.interpolate import make_interp_spline
from PyQt5.QtWidgets import QDialog,QApplication,QFileDialog
from PyQt5.QtCore import *
from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import matplotlib.pyplot as plt
import time
import datetime
from datetime import datetime, timedelta
from pyzbar import pyzbar
import cv2
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QMainWindow, QApplication, QGraphicsScene, QGraphicsPixmapItem
from PyQt5 import QtCore, QtGui, QtWidgets

#時間格式
now_output_time = str(datetime.now().strftime('%Y-%m-%d %H-%M-%S'))
com_now_output = str(datetime.now().strftime('%Y-%m-%d'))

#QrCode掃描
def scan_qrcode(qrcode):
    data = pyzbar.decode(qrcode)
    return data[0].data.decode('utf-8')



class Ui_MainWindow(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(Ui_MainWindow, self).__init__(parent)

        self.timer_camera = QtCore.QTimer()
        self.CAM_NUM = 0
        self.count = 0

        self.timer = QTimer()
        self.qrcode_result1 = []
        self.qrcode_result2 = []
        self.qrcode_result3 = []
        self.qrcode_result4 = []
        self.qrcode_result5 = []
        self.qrcode_result6 = []
        self.qrcode_result7 = []
        self.qrcode_result8 = []
    
        
    def browsefile(self):
        #宣告計算變數
        self.CH1_data = []
        self.CH2_data = []
        self.CH3_data = []
        self.CH4_data = []
        self.CH5_data = []
        self.CH6_data = []
        self.CH7_data = []
        self.CH8_data = []
        self.CH_T_On = []
        self.CH_T_Off = []
        self.CH_total = []
        self.slot_high = []
        self.slot_low = []
        self.CH_slot = []
        self.TF_array = []
        #開啟TXT檔案
        self.fname = QFileDialog.getOpenFileName(self, '開啟txt檔案', 'C:\Program Files (x86)', 'txt files (*.txt)') # " C:\python\Learn_Python\Temperature" 是自己的電腦位置路徑
        if(self.fname[0]==""):
            print("no file")
        else:
            if not os.path.isdir('./image'):
                print("Directory 'image' does not exist.")
                os.mkdir('./image')
            if not os.path.isdir('./result'):
                print("Directory 'result' does not exist.")
                os.mkdir('./result')
            if not os.path.isdir('./EGGI_Temperature'):
                print("Directory 'EGGI_Temperature' does not exist.")
                os.mkdir('./EGGI_Temperature')
            if not os.path.isdir('./EGGI_COM'):
                print("Directory 'EGGI_COM' does not exist.")
                os.mkdir('./EGGI_COM')
            self.input_file.setText(self.fname[0])
            self.df = pd.read_csv(self.fname[0], delimiter='\t')
            self.df.columns = ['time', 'index', 'CH1', 'CH2', 'CH3', 'CH4', 'CH5', 'CH6', 'CH7', 'CH8']  # 在開啟檔案上面新增一行
            print("Open file(.txt) >> " + str(self.fname[0]))
            print("-" * 100)
            print(self.df)
            print("-" * 100)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1533, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 84, 1521, 727))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Sulink = QtWidgets.QWidget()
        self.tab_Sulink.setObjectName("tab_Sulink")
        self.Input_box = QtWidgets.QGroupBox(self.tab_Sulink)
        self.Input_box.setGeometry(QtCore.QRect(10, 6, 711, 169))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Input_box.setFont(font)
        self.Input_box.setStyleSheet("QGroupBox {\n"
"            border-color: rgb(156, 156, 156);\n"
"        }")
        self.Input_box.setObjectName("Input_box")
        self.btn_opentxt = QtWidgets.QPushButton(self.Input_box)
        self.btn_opentxt.setGeometry(QtCore.QRect(600, 24, 91, 43))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.btn_opentxt.setFont(font)
        self.btn_opentxt.setObjectName("btn_opentxt")
        self.btn_save = QtWidgets.QPushButton(self.Input_box)
        self.btn_save.setGeometry(QtCore.QRect(600, 66, 91, 43))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.btn_clean = QtWidgets.QPushButton(self.Input_box)
        self.btn_clean.setGeometry(QtCore.QRect(600, 108, 91, 43))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_clean.setFont(font)
        self.btn_clean.setObjectName("btn_clean")
        self.layoutWidget = QtWidgets.QWidget(self.Input_box)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 581, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.gridLayout_2.addWidget(self.label_name, 0, 0, 1, 1)
        self.input_name = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(False)
        self.input_name.setFont(font)
        self.input_name.setObjectName("input_name")
        self.gridLayout_2.addWidget(self.input_name, 0, 1, 1, 1)
        self.label_datetime = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_datetime.setFont(font)
        self.label_datetime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_datetime.setObjectName("label_datetime")
        self.gridLayout_2.addWidget(self.label_datetime, 0, 2, 1, 1)
        self.output_datetime = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(False)
        self.output_datetime.setFont(font)
        self.output_datetime.setObjectName("output_datetime")
        self.gridLayout_2.addWidget(self.output_datetime, 0, 3, 1, 1)
        self.label_txt_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_txt_2.setFont(font)
        self.label_txt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_txt_2.setObjectName("label_txt_2")
        self.gridLayout_2.addWidget(self.label_txt_2, 1, 0, 1, 1)
        self.input_file = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(False)
        self.input_file.setFont(font)
        self.input_file.setObjectName("input_file")
        self.gridLayout_2.addWidget(self.input_file, 1, 1, 1, 3)
        self.Chart_box = QtWidgets.QGroupBox(self.tab_Sulink)
        self.Chart_box.setGeometry(QtCore.QRect(10, 180, 711, 493))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Chart_box.setFont(font)
        self.Chart_box.setObjectName("Chart_box")
        self.splitter_2 = QtWidgets.QSplitter(self.Chart_box)
        self.splitter_2.setGeometry(QtCore.QRect(16, 156, 0, 0))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.widget_6 = QtWidgets.QWidget(self.splitter_2)
        self.widget_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_6.setObjectName("widget_6")
        self.widget_7 = QtWidgets.QWidget(self.splitter_2)
        self.widget_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_7.setObjectName("widget_7")
        self.widget_8 = QtWidgets.QWidget(self.splitter_2)
        self.widget_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_8.setObjectName("widget_8")
        self.widget_5 = QtWidgets.QWidget(self.splitter_2)
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Chart_box)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 36, 691, 427))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ch6_display = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ch6_display.setObjectName("ch6_display")
        self.gridLayout_3.addWidget(self.ch6_display, 3, 1, 1, 1)
        self.ch7_display = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ch7_display.setObjectName("ch7_display")
        self.gridLayout_3.addWidget(self.ch7_display, 3, 2, 1, 1)
        self.ch8_display = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ch8_display.setObjectName("ch8_display")
        self.gridLayout_3.addWidget(self.ch8_display, 3, 3, 1, 1)
        self.ch3_display = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ch3_display.setObjectName("ch3_display")
        self.gridLayout_3.addWidget(self.ch3_display, 1, 2, 1, 1)
        self.ch3_chart = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.ch3_chart.setObjectName("ch3_chart")
        self.gridLayout_3.addWidget(self.ch3_chart, 0, 2, 1, 1)
        self.ch7_chart = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.ch7_chart.setObjectName("ch7_chart")
        self.gridLayout_3.addWidget(self.ch7_chart, 2, 2, 1, 1)
        self.ch8_chart = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.ch8_chart.setObjectName("ch8_chart")
        self.gridLayout_3.addWidget(self.ch8_chart, 2, 3, 1, 1)
        self.ch4_chart = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.ch4_chart.setObjectName("ch4_chart")
        self.gridLayout_3.addWidget(self.ch4_chart, 0, 3, 1, 1)
        self.ch1_display = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ch1_display.setObjectName("ch1_display")
        self.gridLayout_3.addWidget(self.ch1_display, 1, 0, 1, 1)
        self.ch1_chart = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.ch1_chart.setObjectName("ch1_chart")
        self.gridLayout_3.addWidget(self.ch1_chart, 0, 0, 1, 1)
        self.ch6_chart = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.ch6_chart.setObjectName("ch6_chart")
        self.gridLayout_3.addWidget(self.ch6_chart, 2, 1, 1, 1)
        self.ch2_display = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ch2_display.setObjectName("ch2_display")
        self.gridLayout_3.addWidget(self.ch2_display, 1, 1, 1, 1)
        self.ch5_chart = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.ch5_chart.setObjectName("ch5_chart")
        self.gridLayout_3.addWidget(self.ch5_chart, 2, 0, 1, 1)
        self.ch2_chart = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.ch2_chart.setObjectName("ch2_chart")
        self.gridLayout_3.addWidget(self.ch2_chart, 0, 1, 1, 1)
        self.ch5_display = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ch5_display.setObjectName("ch5_display")
        self.gridLayout_3.addWidget(self.ch5_display, 3, 0, 1, 1)
        self.ch4_display = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ch4_display.setObjectName("ch4_display")
        self.gridLayout_3.addWidget(self.ch4_display, 1, 3, 1, 1)
        self.Result_box = QtWidgets.QGroupBox(self.tab_Sulink)
        self.Result_box.setGeometry(QtCore.QRect(730, 6, 771, 667))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Result_box.setFont(font)
        self.Result_box.setObjectName("Result_box")
        self.layoutWidget1 = QtWidgets.QWidget(self.Result_box)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 797, 427))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_ch3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ch3.setFont(font)
        self.label_ch3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch3.setObjectName("label_ch3")
        self.gridLayout.addWidget(self.label_ch3, 3, 0, 1, 1)
        self.label_qrcode = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_qrcode.setFont(font)
        self.label_qrcode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_qrcode.setObjectName("label_qrcode")
        self.gridLayout.addWidget(self.label_qrcode, 0, 2, 1, 1)
        self.ch1_slope = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch1_slope.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_slope.setObjectName("ch1_slope")
        self.gridLayout.addWidget(self.ch1_slope, 1, 5, 1, 1)
        self.label_T_On = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_T_On.setFont(font)
        self.label_T_On.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T_On.setObjectName("label_T_On")
        self.gridLayout.addWidget(self.label_T_On, 0, 3, 1, 1)
        self.ch4_T_Off = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch4_T_Off.setAlignment(QtCore.Qt.AlignCenter)
        self.ch4_T_Off.setObjectName("ch4_T_Off")
        self.gridLayout.addWidget(self.ch4_T_Off, 4, 4, 1, 1)
        self.ch3_T_On = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch3_T_On.setAlignment(QtCore.Qt.AlignCenter)
        self.ch3_T_On.setObjectName("ch3_T_On")
        self.gridLayout.addWidget(self.ch3_T_On, 3, 3, 1, 1)
        self.ch7_T_On = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch7_T_On.setAlignment(QtCore.Qt.AlignCenter)
        self.ch7_T_On.setObjectName("ch7_T_On")
        self.gridLayout.addWidget(self.ch7_T_On, 7, 3, 1, 1)
        self.ch1_qrcodelable = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch1_qrcodelable.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_qrcodelable.setObjectName("ch1_qrcodelable")
        self.gridLayout.addWidget(self.ch1_qrcodelable, 1, 2, 1, 1)
        self.ch6_PF = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch6_PF.setAlignment(QtCore.Qt.AlignCenter)
        self.ch6_PF.setObjectName("ch6_PF")
        self.gridLayout.addWidget(self.ch6_PF, 6, 6, 1, 1)
        self.ch6_T_On = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch6_T_On.setAlignment(QtCore.Qt.AlignCenter)
        self.ch6_T_On.setObjectName("ch6_T_On")
        self.gridLayout.addWidget(self.ch6_T_On, 6, 3, 1, 1)
        self.ch8_qrcodelable = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch8_qrcodelable.setAlignment(QtCore.Qt.AlignCenter)
        self.ch8_qrcodelable.setObjectName("ch8_qrcodelable")
        self.gridLayout.addWidget(self.ch8_qrcodelable, 8, 2, 1, 1)
        self.ch8_PF = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch8_PF.setAlignment(QtCore.Qt.AlignCenter)
        self.ch8_PF.setObjectName("ch8_PF")
        self.gridLayout.addWidget(self.ch8_PF, 8, 6, 1, 1)
        self.ch7_slope = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch7_slope.setAlignment(QtCore.Qt.AlignCenter)
        self.ch7_slope.setObjectName("ch7_slope")
        self.gridLayout.addWidget(self.ch7_slope, 7, 5, 1, 1)
        self.ch3_qrcodelable = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch3_qrcodelable.setAlignment(QtCore.Qt.AlignCenter)
        self.ch3_qrcodelable.setObjectName("ch3_qrcodelable")
        self.gridLayout.addWidget(self.ch3_qrcodelable, 3, 2, 1, 1)
        self.ch3_slope = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch3_slope.setAlignment(QtCore.Qt.AlignCenter)
        self.ch3_slope.setObjectName("ch3_slope")
        self.gridLayout.addWidget(self.ch3_slope, 3, 5, 1, 1)
        self.label_ch1 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ch1.setFont(font)
        self.label_ch1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch1.setObjectName("label_ch1")
        self.gridLayout.addWidget(self.label_ch1, 1, 0, 1, 1)
        self.ch1_qrcode = QtWidgets.QPushButton(self.layoutWidget1)
        self.ch1_qrcode.setObjectName("ch1_qrcode")
        self.gridLayout.addWidget(self.ch1_qrcode, 1, 1, 1, 1)
        self.ch1_T_Off = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch1_T_Off.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_T_Off.setObjectName("ch1_T_Off")
        self.gridLayout.addWidget(self.ch1_T_Off, 1, 4, 1, 1)
        self.ch2_T_On = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch2_T_On.setAlignment(QtCore.Qt.AlignCenter)
        self.ch2_T_On.setObjectName("ch2_T_On")
        self.gridLayout.addWidget(self.ch2_T_On, 2, 3, 1, 1)
        self.ch7_qrcode = QtWidgets.QPushButton(self.layoutWidget1)
        self.ch7_qrcode.setObjectName("ch7_qrcode")
        self.gridLayout.addWidget(self.ch7_qrcode, 7, 1, 1, 1)
        self.ch4_qrcodelable = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch4_qrcodelable.setAlignment(QtCore.Qt.AlignCenter)
        self.ch4_qrcodelable.setObjectName("ch4_qrcodelable")
        self.gridLayout.addWidget(self.ch4_qrcodelable, 4, 2, 1, 1)
        self.label_Slope = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_Slope.setFont(font)
        self.label_Slope.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Slope.setObjectName("label_Slope")
        self.gridLayout.addWidget(self.label_Slope, 0, 5, 1, 1)
        self.label_ch5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ch5.setFont(font)
        self.label_ch5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch5.setObjectName("label_ch5")
        self.gridLayout.addWidget(self.label_ch5, 5, 0, 1, 1)
        self.ch3_qrcode = QtWidgets.QPushButton(self.layoutWidget1)
        self.ch3_qrcode.setObjectName("ch3_qrcode")
        self.gridLayout.addWidget(self.ch3_qrcode, 3, 1, 1, 1)
        self.ch4_qrcode = QtWidgets.QPushButton(self.layoutWidget1)
        self.ch4_qrcode.setObjectName("ch4_qrcode")
        self.gridLayout.addWidget(self.ch4_qrcode, 4, 1, 1, 1)
        self.ch8_slope = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch8_slope.setAlignment(QtCore.Qt.AlignCenter)
        self.ch8_slope.setObjectName("ch8_slope")
        self.gridLayout.addWidget(self.ch8_slope, 8, 5, 1, 1)
        self.ch1_T_On = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch1_T_On.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_T_On.setObjectName("ch1_T_On")
        self.gridLayout.addWidget(self.ch1_T_On, 1, 3, 1, 1)
        self.ch7_T_Off = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch7_T_Off.setAlignment(QtCore.Qt.AlignCenter)
        self.ch7_T_Off.setObjectName("ch7_T_Off")
        self.gridLayout.addWidget(self.ch7_T_Off, 7, 4, 1, 1)
        self.ch2_PF = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch2_PF.setAlignment(QtCore.Qt.AlignCenter)
        self.ch2_PF.setObjectName("ch2_PF")
        self.gridLayout.addWidget(self.ch2_PF, 2, 6, 1, 1)
        self.ch4_slope = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch4_slope.setAlignment(QtCore.Qt.AlignCenter)
        self.ch4_slope.setObjectName("ch4_slope")
        self.gridLayout.addWidget(self.ch4_slope, 4, 5, 1, 1)
        self.ch2_qrcode = QtWidgets.QPushButton(self.layoutWidget1)
        self.ch2_qrcode.setObjectName("ch2_qrcode")
        self.gridLayout.addWidget(self.ch2_qrcode, 2, 1, 1, 1)
        self.ch1_PF = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch1_PF.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_PF.setObjectName("ch1_PF")
        self.gridLayout.addWidget(self.ch1_PF, 1, 6, 1, 1)
        self.ch3_PF = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch3_PF.setAlignment(QtCore.Qt.AlignCenter)
        self.ch3_PF.setObjectName("ch3_PF")
        self.gridLayout.addWidget(self.ch3_PF, 3, 6, 1, 1)
        self.label_ch4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ch4.setFont(font)
        self.label_ch4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch4.setObjectName("label_ch4")
        self.gridLayout.addWidget(self.label_ch4, 4, 0, 1, 1)
        self.ch5_slope = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch5_slope.setAlignment(QtCore.Qt.AlignCenter)
        self.ch5_slope.setObjectName("ch5_slope")
        self.gridLayout.addWidget(self.ch5_slope, 5, 5, 1, 1)
        self.ch8_qrcode = QtWidgets.QPushButton(self.layoutWidget1)
        self.ch8_qrcode.setObjectName("ch8_qrcode")
        self.gridLayout.addWidget(self.ch8_qrcode, 8, 1, 1, 1)
        self.label_T_Off = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_T_Off.setFont(font)
        self.label_T_Off.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T_Off.setObjectName("label_T_Off")
        self.gridLayout.addWidget(self.label_T_Off, 0, 4, 1, 1)
        self.ch5_PF = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch5_PF.setAlignment(QtCore.Qt.AlignCenter)
        self.ch5_PF.setObjectName("ch5_PF")
        self.gridLayout.addWidget(self.ch5_PF, 5, 6, 1, 1)
        self.ch5_qrcode = QtWidgets.QPushButton(self.layoutWidget1)
        self.ch5_qrcode.setObjectName("ch5_qrcode")
        self.gridLayout.addWidget(self.ch5_qrcode, 5, 1, 1, 1)
        self.label_T_On_14 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_T_On_14.setFont(font)
        self.label_T_On_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T_On_14.setObjectName("label_T_On_14")
        self.gridLayout.addWidget(self.label_T_On_14, 0, 6, 1, 1)
        self.label_ch7 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ch7.setFont(font)
        self.label_ch7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch7.setObjectName("label_ch7")
        self.gridLayout.addWidget(self.label_ch7, 7, 0, 1, 1)
        self.ch5_T_Off = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch5_T_Off.setAlignment(QtCore.Qt.AlignCenter)
        self.ch5_T_Off.setObjectName("ch5_T_Off")
        self.gridLayout.addWidget(self.ch5_T_Off, 5, 4, 1, 1)
        self.label_ch2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ch2.setFont(font)
        self.label_ch2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch2.setObjectName("label_ch2")
        self.gridLayout.addWidget(self.label_ch2, 2, 0, 1, 1)
        self.ch5_T_On = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch5_T_On.setAlignment(QtCore.Qt.AlignCenter)
        self.ch5_T_On.setObjectName("ch5_T_On")
        self.gridLayout.addWidget(self.ch5_T_On, 5, 3, 1, 1)
        self.ch4_PF = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch4_PF.setAlignment(QtCore.Qt.AlignCenter)
        self.ch4_PF.setObjectName("ch4_PF")
        self.gridLayout.addWidget(self.ch4_PF, 4, 6, 1, 1)
        self.ch6_qrcode = QtWidgets.QPushButton(self.layoutWidget1)
        self.ch6_qrcode.setObjectName("ch6_qrcode")
        self.gridLayout.addWidget(self.ch6_qrcode, 6, 1, 1, 1)
        self.ch7_PF = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch7_PF.setAlignment(QtCore.Qt.AlignCenter)
        self.ch7_PF.setObjectName("ch7_PF")
        self.gridLayout.addWidget(self.ch7_PF, 7, 6, 1, 1)
        self.ch8_T_Off = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch8_T_Off.setAlignment(QtCore.Qt.AlignCenter)
        self.ch8_T_Off.setObjectName("ch8_T_Off")
        self.gridLayout.addWidget(self.ch8_T_Off, 8, 4, 1, 1)
        self.ch8_T_On = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch8_T_On.setAlignment(QtCore.Qt.AlignCenter)
        self.ch8_T_On.setObjectName("ch8_T_On")
        self.gridLayout.addWidget(self.ch8_T_On, 8, 3, 1, 1)
        self.label_ch8 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ch8.setFont(font)
        self.label_ch8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch8.setObjectName("label_ch8")
        self.gridLayout.addWidget(self.label_ch8, 8, 0, 1, 1)
        self.ch6_qrcodelable = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch6_qrcodelable.setAlignment(QtCore.Qt.AlignCenter)
        self.ch6_qrcodelable.setObjectName("ch6_qrcodelable")
        self.gridLayout.addWidget(self.ch6_qrcodelable, 6, 2, 1, 1)
        self.ch2_qrcodelable = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch2_qrcodelable.setAlignment(QtCore.Qt.AlignCenter)
        self.ch2_qrcodelable.setObjectName("ch2_qrcodelable")
        self.gridLayout.addWidget(self.ch2_qrcodelable, 2, 2, 1, 1)
        self.ch2_slope = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch2_slope.setAlignment(QtCore.Qt.AlignCenter)
        self.ch2_slope.setObjectName("ch2_slope")
        self.gridLayout.addWidget(self.ch2_slope, 2, 5, 1, 1)
        self.label_ch6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ch6.setFont(font)
        self.label_ch6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch6.setObjectName("label_ch6")
        self.gridLayout.addWidget(self.label_ch6, 6, 0, 1, 1)
        self.ch5_qrcodelable = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch5_qrcodelable.setAlignment(QtCore.Qt.AlignCenter)
        self.ch5_qrcodelable.setObjectName("ch5_qrcodelable")
        self.gridLayout.addWidget(self.ch5_qrcodelable, 5, 2, 1, 1)
        self.ch6_T_Off = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch6_T_Off.setAlignment(QtCore.Qt.AlignCenter)
        self.ch6_T_Off.setObjectName("ch6_T_Off")
        self.gridLayout.addWidget(self.ch6_T_Off, 6, 4, 1, 1)
        self.ch3_T_Off = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch3_T_Off.setAlignment(QtCore.Qt.AlignCenter)
        self.ch3_T_Off.setObjectName("ch3_T_Off")
        self.gridLayout.addWidget(self.ch3_T_Off, 3, 4, 1, 1)
        self.ch2_T_Off = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch2_T_Off.setAlignment(QtCore.Qt.AlignCenter)
        self.ch2_T_Off.setObjectName("ch2_T_Off")
        self.gridLayout.addWidget(self.ch2_T_Off, 2, 4, 1, 1)
        self.ch4_T_On = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch4_T_On.setAlignment(QtCore.Qt.AlignCenter)
        self.ch4_T_On.setObjectName("ch4_T_On")
        self.gridLayout.addWidget(self.ch4_T_On, 4, 3, 1, 1)
        self.ch6_slope = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch6_slope.setAlignment(QtCore.Qt.AlignCenter)
        self.ch6_slope.setObjectName("ch6_slope")
        self.gridLayout.addWidget(self.ch6_slope, 6, 5, 1, 1)
        self.ch7_qrcodelable = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ch7_qrcodelable.setAlignment(QtCore.Qt.AlignCenter)
        self.ch7_qrcodelable.setObjectName("ch7_qrcodelable")
        self.gridLayout.addWidget(self.ch7_qrcodelable, 7, 2, 1, 1)
        self.label_qrcode_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_qrcode_3.setFont(font)
        self.label_qrcode_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_qrcode_3.setObjectName("label_qrcode_3")
        self.gridLayout.addWidget(self.label_qrcode_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_Sulink, "")
        self.tab_hardware = QtWidgets.QWidget()
        self.tab_hardware.setObjectName("tab_hardware")
        self.com_Input_box = QtWidgets.QGroupBox(self.tab_hardware)
        self.com_Input_box.setGeometry(QtCore.QRect(10, 6, 711, 169))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.com_Input_box.setFont(font)
        self.com_Input_box.setStyleSheet("border-color:black")
        self.com_Input_box.setObjectName("com_Input_box")
        self.com_btn_opentxt = QtWidgets.QPushButton(self.com_Input_box)
        self.com_btn_opentxt.setGeometry(QtCore.QRect(600, 24, 91, 43))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.com_btn_opentxt.setFont(font)
        self.com_btn_opentxt.setObjectName("com_btn_opentxt")
        self.com_btn_save = QtWidgets.QPushButton(self.com_Input_box)
        self.com_btn_save.setGeometry(QtCore.QRect(600, 66, 91, 43))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.com_btn_save.setFont(font)
        self.com_btn_save.setObjectName("com_btn_save")
        self.com_btn_clean = QtWidgets.QPushButton(self.com_Input_box)
        self.com_btn_clean.setGeometry(QtCore.QRect(600, 108, 91, 43))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.com_btn_clean.setFont(font)
        self.com_btn_clean.setObjectName("com_btn_clean")
        self.layoutWidget_4 = QtWidgets.QWidget(self.com_Input_box)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 30, 581, 121))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.com_label_name = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.com_label_name.setFont(font)
        self.com_label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.com_label_name.setObjectName("com_label_name")
        self.gridLayout_4.addWidget(self.com_label_name, 0, 0, 1, 1)
        self.com_input_name = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.com_input_name.setFont(font)
        self.com_input_name.setObjectName("com_input_name")
        self.gridLayout_4.addWidget(self.com_input_name, 0, 1, 1, 1)
        self.com_label_datetime = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.com_label_datetime.setFont(font)
        self.com_label_datetime.setAlignment(QtCore.Qt.AlignCenter)
        self.com_label_datetime.setObjectName("com_label_datetime")
        self.gridLayout_4.addWidget(self.com_label_datetime, 0, 2, 1, 1)
        self.com_output_datetime = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.com_output_datetime.setFont(font)
        self.com_output_datetime.setObjectName("com_output_datetime")
        self.gridLayout_4.addWidget(self.com_output_datetime, 0, 3, 1, 1)
        self.com_label_txt = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.com_label_txt.setFont(font)
        self.com_label_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.com_label_txt.setObjectName("com_label_txt")
        self.gridLayout_4.addWidget(self.com_label_txt, 1, 0, 1, 1)
        self.com_input_file = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.com_input_file.setFont(font)
        self.com_input_file.setObjectName("com_input_file")
        self.gridLayout_4.addWidget(self.com_input_file, 1, 1, 1, 3)
        self.com_result = QtWidgets.QGroupBox(self.tab_hardware)
        self.com_result.setGeometry(QtCore.QRect(730, 6, 771, 673))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.com_result.setFont(font)
        self.com_result.setObjectName("com_result")
        self.layoutWidget2 = QtWidgets.QWidget(self.com_result)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 42, 731, 403))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.com_ch4_qrcode = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch4_qrcode.setFont(font)
        self.com_ch4_qrcode.setObjectName("com_ch4_qrcode")
        self.gridLayout_5.addWidget(self.com_ch4_qrcode, 4, 2, 1, 1)
        self.com_ch3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch3.setFont(font)
        self.com_ch3.setAlignment(QtCore.Qt.AlignCenter)
        self.com_ch3.setObjectName("com_ch3")
        self.gridLayout_5.addWidget(self.com_ch3, 3, 0, 1, 1)
        self.com_ch3_well = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch3_well.setFont(font)
        self.com_ch3_well.setObjectName("com_ch3_well")
        self.gridLayout_5.addWidget(self.com_ch3_well, 3, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 1, 1, 1)
        self.com_ch7_well = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch7_well.setFont(font)
        self.com_ch7_well.setObjectName("com_ch7_well")
        self.gridLayout_5.addWidget(self.com_ch7_well, 7, 3, 1, 1)
        self.com_ch2_well = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch2_well.setFont(font)
        self.com_ch2_well.setObjectName("com_ch2_well")
        self.gridLayout_5.addWidget(self.com_ch2_well, 2, 3, 1, 1)
        self.com_btn_ch2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.com_btn_ch2.setObjectName("com_btn_ch2")
        self.gridLayout_5.addWidget(self.com_btn_ch2, 2, 1, 1, 1)
        self.com_ch1_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch1_pf.setFont(font)
        self.com_ch1_pf.setObjectName("com_ch1_pf")
        self.gridLayout_5.addWidget(self.com_ch1_pf, 1, 4, 1, 1)
        self.com_btn_ch4 = QtWidgets.QPushButton(self.layoutWidget2)
        self.com_btn_ch4.setObjectName("com_btn_ch4")
        self.gridLayout_5.addWidget(self.com_btn_ch4, 4, 1, 1, 1)
        self.com_btn_ch7 = QtWidgets.QPushButton(self.layoutWidget2)
        self.com_btn_ch7.setObjectName("com_btn_ch7")
        self.gridLayout_5.addWidget(self.com_btn_ch7, 7, 1, 1, 1)
        self.com_btn_ch5 = QtWidgets.QPushButton(self.layoutWidget2)
        self.com_btn_ch5.setObjectName("com_btn_ch5")
        self.gridLayout_5.addWidget(self.com_btn_ch5, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 4, 1, 1)
        self.com_ch7_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch7_pf.setFont(font)
        self.com_ch7_pf.setObjectName("com_ch7_pf")
        self.gridLayout_5.addWidget(self.com_ch7_pf, 7, 4, 1, 1)
        self.com_ch1_qrcode = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch1_qrcode.setFont(font)
        self.com_ch1_qrcode.setObjectName("com_ch1_qrcode")
        self.gridLayout_5.addWidget(self.com_ch1_qrcode, 1, 2, 1, 1)
        self.com_ch8 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch8.setFont(font)
        self.com_ch8.setAlignment(QtCore.Qt.AlignCenter)
        self.com_ch8.setObjectName("com_ch8")
        self.gridLayout_5.addWidget(self.com_ch8, 8, 0, 1, 1)
        self.com_ch6 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch6.setFont(font)
        self.com_ch6.setAlignment(QtCore.Qt.AlignCenter)
        self.com_ch6.setObjectName("com_ch6")
        self.gridLayout_5.addWidget(self.com_ch6, 6, 0, 1, 1)
        self.com_ch8_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch8_pf.setFont(font)
        self.com_ch8_pf.setObjectName("com_ch8_pf")
        self.gridLayout_5.addWidget(self.com_ch8_pf, 8, 4, 1, 1)
        self.com_ch3_qrcode = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch3_qrcode.setFont(font)
        self.com_ch3_qrcode.setObjectName("com_ch3_qrcode")
        self.gridLayout_5.addWidget(self.com_ch3_qrcode, 3, 2, 1, 1)
        self.com_ch6_well = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch6_well.setFont(font)
        self.com_ch6_well.setObjectName("com_ch6_well")
        self.gridLayout_5.addWidget(self.com_ch6_well, 6, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 5, 1, 1)
        self.com_ch2_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch2_pf.setFont(font)
        self.com_ch2_pf.setObjectName("com_ch2_pf")
        self.gridLayout_5.addWidget(self.com_ch2_pf, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 3, 1, 1)
        self.com_ch7_qrcode = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch7_qrcode.setFont(font)
        self.com_ch7_qrcode.setObjectName("com_ch7_qrcode")
        self.gridLayout_5.addWidget(self.com_ch7_qrcode, 7, 2, 1, 1)
        self.com_btn_ch1 = QtWidgets.QPushButton(self.layoutWidget2)
        self.com_btn_ch1.setObjectName("com_btn_ch1")
        self.gridLayout_5.addWidget(self.com_btn_ch1, 1, 1, 1, 1)
        self.com_ch1_well = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch1_well.setFont(font)
        self.com_ch1_well.setObjectName("com_ch1_well")
        self.gridLayout_5.addWidget(self.com_ch1_well, 1, 3, 1, 1)
        self.com_ch6_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch6_pf.setFont(font)
        self.com_ch6_pf.setObjectName("com_ch6_pf")
        self.gridLayout_5.addWidget(self.com_ch6_pf, 6, 4, 1, 1)
        self.com_ch5 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch5.setFont(font)
        self.com_ch5.setAlignment(QtCore.Qt.AlignCenter)
        self.com_ch5.setObjectName("com_ch5")
        self.gridLayout_5.addWidget(self.com_ch5, 5, 0, 1, 1)
        self.com_ch7 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch7.setFont(font)
        self.com_ch7.setAlignment(QtCore.Qt.AlignCenter)
        self.com_ch7.setObjectName("com_ch7")
        self.gridLayout_5.addWidget(self.com_ch7, 7, 0, 1, 1)
        self.com_btn_ch6 = QtWidgets.QPushButton(self.layoutWidget2)
        self.com_btn_ch6.setObjectName("com_btn_ch6")
        self.gridLayout_5.addWidget(self.com_btn_ch6, 6, 1, 1, 1)
        self.com_ch4_well = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch4_well.setFont(font)
        self.com_ch4_well.setObjectName("com_ch4_well")
        self.gridLayout_5.addWidget(self.com_ch4_well, 4, 3, 1, 1)
        self.com_ch5_qrcode = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch5_qrcode.setFont(font)
        self.com_ch5_qrcode.setObjectName("com_ch5_qrcode")
        self.gridLayout_5.addWidget(self.com_ch5_qrcode, 5, 2, 1, 1)
        self.com_ch4_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch4_pf.setFont(font)
        self.com_ch4_pf.setObjectName("com_ch4_pf")
        self.gridLayout_5.addWidget(self.com_ch4_pf, 4, 4, 1, 1)
        self.com_ch1 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch1.setFont(font)
        self.com_ch1.setAlignment(QtCore.Qt.AlignCenter)
        self.com_ch1.setObjectName("com_ch1")
        self.gridLayout_5.addWidget(self.com_ch1, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 2, 1, 1)
        self.com_ch4 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch4.setFont(font)
        self.com_ch4.setAlignment(QtCore.Qt.AlignCenter)
        self.com_ch4.setObjectName("com_ch4")
        self.gridLayout_5.addWidget(self.com_ch4, 4, 0, 1, 1)
        self.com_btn_ch8 = QtWidgets.QPushButton(self.layoutWidget2)
        self.com_btn_ch8.setObjectName("com_btn_ch8")
        self.gridLayout_5.addWidget(self.com_btn_ch8, 8, 1, 1, 1)
        self.com_ch8_well = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch8_well.setFont(font)
        self.com_ch8_well.setObjectName("com_ch8_well")
        self.gridLayout_5.addWidget(self.com_ch8_well, 8, 3, 1, 1)
        self.com_ch6_qrcode = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch6_qrcode.setFont(font)
        self.com_ch6_qrcode.setObjectName("com_ch6_qrcode")
        self.gridLayout_5.addWidget(self.com_ch6_qrcode, 6, 2, 1, 1)
        self.com_ch2_qrcode = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch2_qrcode.setFont(font)
        self.com_ch2_qrcode.setObjectName("com_ch2_qrcode")
        self.gridLayout_5.addWidget(self.com_ch2_qrcode, 2, 2, 1, 1)
        self.com_ch2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch2.setFont(font)
        self.com_ch2.setAlignment(QtCore.Qt.AlignCenter)
        self.com_ch2.setObjectName("com_ch2")
        self.gridLayout_5.addWidget(self.com_ch2, 2, 0, 1, 1)
        self.com_ch5_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch5_pf.setFont(font)
        self.com_ch5_pf.setObjectName("com_ch5_pf")
        self.gridLayout_5.addWidget(self.com_ch5_pf, 5, 4, 1, 1)
        self.com_ch5_well = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch5_well.setFont(font)
        self.com_ch5_well.setObjectName("com_ch5_well")
        self.gridLayout_5.addWidget(self.com_ch5_well, 5, 3, 1, 1)
        self.com_btn_ch3 = QtWidgets.QPushButton(self.layoutWidget2)
        self.com_btn_ch3.setObjectName("com_btn_ch3")
        self.gridLayout_5.addWidget(self.com_btn_ch3, 3, 1, 1, 1)
        self.com_ch3_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch3_pf.setFont(font)
        self.com_ch3_pf.setObjectName("com_ch3_pf")
        self.gridLayout_5.addWidget(self.com_ch3_pf, 3, 4, 1, 1)
        self.com_ch8_qrcode = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.com_ch8_qrcode.setFont(font)
        self.com_ch8_qrcode.setObjectName("com_ch8_qrcode")
        self.gridLayout_5.addWidget(self.com_ch8_qrcode, 8, 2, 1, 1)
        self.com_ch1_top = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch1_top.setFont(font)
        self.com_ch1_top.setObjectName("com_ch1_top")
        self.gridLayout_5.addWidget(self.com_ch1_top, 1, 5, 1, 1)
        self.com_ch2_top = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch2_top.setFont(font)
        self.com_ch2_top.setObjectName("com_ch2_top")
        self.gridLayout_5.addWidget(self.com_ch2_top, 2, 5, 1, 1)
        self.com_ch3_top = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch3_top.setFont(font)
        self.com_ch3_top.setObjectName("com_ch3_top")
        self.gridLayout_5.addWidget(self.com_ch3_top, 3, 5, 1, 1)
        self.com_ch4_top = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch4_top.setFont(font)
        self.com_ch4_top.setObjectName("com_ch4_top")
        self.gridLayout_5.addWidget(self.com_ch4_top, 4, 5, 1, 1)
        self.com_ch5_top = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch5_top.setFont(font)
        self.com_ch5_top.setObjectName("com_ch5_top")
        self.gridLayout_5.addWidget(self.com_ch5_top, 5, 5, 1, 1)
        self.com_ch6_top = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch6_top.setFont(font)
        self.com_ch6_top.setObjectName("com_ch6_top")
        self.gridLayout_5.addWidget(self.com_ch6_top, 6, 5, 1, 1)
        self.com_ch7_top = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch7_top.setFont(font)
        self.com_ch7_top.setObjectName("com_ch7_top")
        self.gridLayout_5.addWidget(self.com_ch7_top, 7, 5, 1, 1)
        self.com_ch8_top = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch8_top.setFont(font)
        self.com_ch8_top.setObjectName("com_ch8_top")
        self.gridLayout_5.addWidget(self.com_ch8_top, 8, 5, 1, 1)
        self.com_ch1_top_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch1_top_pf.setFont(font)
        self.com_ch1_top_pf.setObjectName("com_ch1_top_pf")
        self.gridLayout_5.addWidget(self.com_ch1_top_pf, 1, 6, 1, 1)
        self.com_ch2_top_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch2_top_pf.setFont(font)
        self.com_ch2_top_pf.setObjectName("com_ch2_top_pf")
        self.gridLayout_5.addWidget(self.com_ch2_top_pf, 2, 6, 1, 1)
        self.com_ch3_top_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch3_top_pf.setFont(font)
        self.com_ch3_top_pf.setObjectName("com_ch3_top_pf")
        self.gridLayout_5.addWidget(self.com_ch3_top_pf, 3, 6, 1, 1)
        self.com_ch4_top_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch4_top_pf.setFont(font)
        self.com_ch4_top_pf.setObjectName("com_ch4_top_pf")
        self.gridLayout_5.addWidget(self.com_ch4_top_pf, 4, 6, 1, 1)
        self.com_ch5_top_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch5_top_pf.setFont(font)
        self.com_ch5_top_pf.setObjectName("com_ch5_top_pf")
        self.gridLayout_5.addWidget(self.com_ch5_top_pf, 5, 6, 1, 1)
        self.com_ch6_top_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch6_top_pf.setFont(font)
        self.com_ch6_top_pf.setObjectName("com_ch6_top_pf")
        self.gridLayout_5.addWidget(self.com_ch6_top_pf, 6, 6, 1, 1)
        self.com_ch7_top_pf = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch7_top_pf.setFont(font)
        self.com_ch7_top_pf.setObjectName("com_ch7_top_pf")
        self.gridLayout_5.addWidget(self.com_ch7_top_pf, 7, 6, 1, 1)
        self.com_ch1_pf_17 = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.com_ch1_pf_17.setFont(font)
        self.com_ch1_pf_17.setObjectName("com_ch1_pf_17")
        self.gridLayout_5.addWidget(self.com_ch1_pf_17, 8, 6, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.com_result)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 486, 731, 75))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 1, 0, 1, 1)
        self.Chart_box_2 = QtWidgets.QGroupBox(self.tab_hardware)
        self.Chart_box_2.setGeometry(QtCore.QRect(10, 180, 711, 499))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Chart_box_2.setFont(font)
        self.Chart_box_2.setObjectName("Chart_box_2")
        self.splitter_3 = QtWidgets.QSplitter(self.Chart_box_2)
        self.splitter_3.setGeometry(QtCore.QRect(16, 156, 0, 0))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.widget_9 = QtWidgets.QWidget(self.splitter_3)
        self.widget_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_9.setObjectName("widget_9")
        self.widget_10 = QtWidgets.QWidget(self.splitter_3)
        self.widget_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_10.setObjectName("widget_10")
        self.widget_11 = QtWidgets.QWidget(self.splitter_3)
        self.widget_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_11.setObjectName("widget_11")
        self.widget_12 = QtWidgets.QWidget(self.splitter_3)
        self.widget_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_12.setObjectName("widget_12")
        self.layoutWidget_3 = QtWidgets.QWidget(self.Chart_box_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 36, 691, 427))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ch6_display_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.ch6_display_2.setObjectName("ch6_display_2")
        self.gridLayout_6.addWidget(self.ch6_display_2, 3, 1, 1, 1)
        self.ch7_display_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.ch7_display_2.setObjectName("ch7_display_2")
        self.gridLayout_6.addWidget(self.ch7_display_2, 3, 2, 1, 1)
        self.ch8_display_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.ch8_display_2.setObjectName("ch8_display_2")
        self.gridLayout_6.addWidget(self.ch8_display_2, 3, 3, 1, 1)
        self.ch3_display_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.ch3_display_2.setObjectName("ch3_display_2")
        self.gridLayout_6.addWidget(self.ch3_display_2, 1, 2, 1, 1)
        self.ch3_chart_2 = QtWidgets.QGraphicsView(self.layoutWidget_3)
        self.ch3_chart_2.setObjectName("ch3_chart_2")
        self.gridLayout_6.addWidget(self.ch3_chart_2, 0, 2, 1, 1)
        self.ch7_chart_2 = QtWidgets.QGraphicsView(self.layoutWidget_3)
        self.ch7_chart_2.setObjectName("ch7_chart_2")
        self.gridLayout_6.addWidget(self.ch7_chart_2, 2, 2, 1, 1)
        self.ch8_chart_2 = QtWidgets.QGraphicsView(self.layoutWidget_3)
        self.ch8_chart_2.setObjectName("ch8_chart_2")
        self.gridLayout_6.addWidget(self.ch8_chart_2, 2, 3, 1, 1)
        self.ch4_chart_2 = QtWidgets.QGraphicsView(self.layoutWidget_3)
        self.ch4_chart_2.setObjectName("ch4_chart_2")
        self.gridLayout_6.addWidget(self.ch4_chart_2, 0, 3, 1, 1)
        self.ch1_display_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.ch1_display_2.setObjectName("ch1_display_2")
        self.gridLayout_6.addWidget(self.ch1_display_2, 1, 0, 1, 1)
        self.ch1_chart_2 = QtWidgets.QGraphicsView(self.layoutWidget_3)
        self.ch1_chart_2.setObjectName("ch1_chart_2")
        self.gridLayout_6.addWidget(self.ch1_chart_2, 0, 0, 1, 1)
        self.ch6_chart_2 = QtWidgets.QGraphicsView(self.layoutWidget_3)
        self.ch6_chart_2.setObjectName("ch6_chart_2")
        self.gridLayout_6.addWidget(self.ch6_chart_2, 2, 1, 1, 1)
        self.ch2_display_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.ch2_display_2.setObjectName("ch2_display_2")
        self.gridLayout_6.addWidget(self.ch2_display_2, 1, 1, 1, 1)
        self.ch5_chart_2 = QtWidgets.QGraphicsView(self.layoutWidget_3)
        self.ch5_chart_2.setObjectName("ch5_chart_2")
        self.gridLayout_6.addWidget(self.ch5_chart_2, 2, 0, 1, 1)
        self.ch2_chart_2 = QtWidgets.QGraphicsView(self.layoutWidget_3)
        self.ch2_chart_2.setObjectName("ch2_chart_2")
        self.gridLayout_6.addWidget(self.ch2_chart_2, 0, 1, 1, 1)
        self.ch5_display_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.ch5_display_2.setObjectName("ch5_display_2")
        self.gridLayout_6.addWidget(self.ch5_display_2, 3, 0, 1, 1)
        self.ch4_display_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.ch4_display_2.setObjectName("ch4_display_2")
        self.gridLayout_6.addWidget(self.ch4_display_2, 1, 3, 1, 1)
        self.tabWidget.addTab(self.tab_hardware, "")
        self.EGGI_Title = QtWidgets.QLabel(self.centralwidget)
        self.EGGI_Title.setGeometry(QtCore.QRect(0, 6, 1521, 79))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(False)
        self.EGGI_Title.setFont(font)
        self.EGGI_Title.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.EGGI_Title.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.EGGI_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.EGGI_Title.setObjectName("EGGI_Title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn_opentxt.clicked.connect(self.browsefile)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "溫度數據監控"))
        self.Input_box.setTitle(_translate("MainWindow", "Input"))
        self.btn_opentxt.setText(_translate("MainWindow", "打開"))
        self.btn_save.setText(_translate("MainWindow", "儲存"))
        self.btn_clean.setText(_translate("MainWindow", "清除"))
        self.label_name.setText(_translate("MainWindow", "操作人員"))
        self.label_datetime.setText(_translate("MainWindow", "日期"))
        self.label_txt_2.setText(_translate("MainWindow", "TXT檔案"))
        self.Chart_box.setTitle(_translate("MainWindow", "Chart"))
        self.ch6_display.setText(_translate("MainWindow", "顯示CH6"))
        self.ch7_display.setText(_translate("MainWindow", "顯示CH7"))
        self.ch8_display.setText(_translate("MainWindow", "顯示CH8"))
        self.ch3_display.setText(_translate("MainWindow", "顯示CH3"))
        self.ch1_display.setText(_translate("MainWindow", "顯示CH1"))
        self.ch2_display.setText(_translate("MainWindow", "顯示CH2"))
        self.ch5_display.setText(_translate("MainWindow", "顯示CH5"))
        self.ch4_display.setText(_translate("MainWindow", "顯示CH4"))
        self.Result_box.setTitle(_translate("MainWindow", "Result"))
        self.label_ch3.setText(_translate("MainWindow", "CH3"))
        self.label_qrcode.setText(_translate("MainWindow", "QRCODE"))
        self.label_T_On.setText(_translate("MainWindow", "T_On"))
        self.label_ch1.setText(_translate("MainWindow", "CH1"))
        self.ch1_qrcode.setText(_translate("MainWindow", "檢測CH1"))
        self.ch7_qrcode.setText(_translate("MainWindow", "檢測CH7"))
        self.label_Slope.setText(_translate("MainWindow", "Slope"))
        self.label_ch5.setText(_translate("MainWindow", "CH5"))
        self.ch3_qrcode.setText(_translate("MainWindow", "檢測CH3"))
        self.ch4_qrcode.setText(_translate("MainWindow", "檢測CH4"))
        self.ch2_qrcode.setText(_translate("MainWindow", "檢測CH2"))
        self.label_ch4.setText(_translate("MainWindow", "CH4"))
        self.ch8_qrcode.setText(_translate("MainWindow", "檢測CH8"))
        self.label_T_Off.setText(_translate("MainWindow", "T_Off"))
        self.ch5_qrcode.setText(_translate("MainWindow", "檢測CH5"))
        self.label_T_On_14.setText(_translate("MainWindow", "PASS/FAIL"))
        self.label_ch7.setText(_translate("MainWindow", "CH7"))
        self.label_ch2.setText(_translate("MainWindow", "CH2"))
        self.ch6_qrcode.setText(_translate("MainWindow", "檢測CH6"))
        self.label_ch8.setText(_translate("MainWindow", "CH8"))
        self.label_ch6.setText(_translate("MainWindow", "CH6"))
        self.label_qrcode_3.setText(_translate("MainWindow", "READ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Sulink), _translate("MainWindow", "溫度保護器"))
        self.com_Input_box.setTitle(_translate("MainWindow", "Input"))
        self.com_btn_opentxt.setText(_translate("MainWindow", "打開"))
        self.com_btn_save.setText(_translate("MainWindow", "儲存"))
        self.com_btn_clean.setText(_translate("MainWindow", "清除"))
        self.com_label_name.setText(_translate("MainWindow", "操作人員"))
        self.com_label_datetime.setText(_translate("MainWindow", "日期"))
        self.com_label_txt.setText(_translate("MainWindow", "TXT檔案"))
        self.com_result.setTitle(_translate("MainWindow", "Result"))
        self.com_ch3.setText(_translate("MainWindow", "CH3"))
        self.label.setText(_translate("MainWindow", "Read"))
        self.com_btn_ch2.setText(_translate("MainWindow", "檢測CH2"))
        self.com_btn_ch4.setText(_translate("MainWindow", "檢測CH4"))
        self.com_btn_ch7.setText(_translate("MainWindow", "檢測CH7"))
        self.com_btn_ch5.setText(_translate("MainWindow", "檢測CH5"))
        self.label_7.setText(_translate("MainWindow", "上加熱片P/F"))
        self.label_3.setText(_translate("MainWindow", "P/F"))
        self.com_ch8.setText(_translate("MainWindow", "CH8"))
        self.com_ch6.setText(_translate("MainWindow", "CH6"))
        self.label_4.setText(_translate("MainWindow", "上加熱片"))
        self.label_2.setText(_translate("MainWindow", "Well溫度"))
        self.com_btn_ch1.setText(_translate("MainWindow", "檢測CH1"))
        self.com_ch5.setText(_translate("MainWindow", "CH5"))
        self.com_ch7.setText(_translate("MainWindow", "CH7"))
        self.com_btn_ch6.setText(_translate("MainWindow", "檢測CH6"))
        self.com_ch1.setText(_translate("MainWindow", "CH1"))
        self.label_9.setText(_translate("MainWindow", "主機編號"))
        self.com_ch4.setText(_translate("MainWindow", "CH4"))
        self.com_btn_ch8.setText(_translate("MainWindow", "檢測CH8"))
        self.com_ch2.setText(_translate("MainWindow", "CH2"))
        self.com_btn_ch3.setText(_translate("MainWindow", "檢測CH3"))
        self.label_5.setText(_translate("MainWindow", "well槽紀錄3分鐘時的溫度58~63(pass)"))
        self.label_6.setText(_translate("MainWindow", "其他(fail)"))
        self.Chart_box_2.setTitle(_translate("MainWindow", "Chart"))
        self.ch6_display_2.setText(_translate("MainWindow", "顯示CH6"))
        self.ch7_display_2.setText(_translate("MainWindow", "顯示CH7"))
        self.ch8_display_2.setText(_translate("MainWindow", "顯示CH8"))
        self.ch3_display_2.setText(_translate("MainWindow", "顯示CH3"))
        self.ch1_display_2.setText(_translate("MainWindow", "顯示CH1"))
        self.ch2_display_2.setText(_translate("MainWindow", "顯示CH2"))
        self.ch5_display_2.setText(_translate("MainWindow", "顯示CH5"))
        self.ch4_display_2.setText(_translate("MainWindow", "顯示CH4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hardware), _translate("MainWindow", "EGGI主機"))
        self.EGGI_Title.setText(_translate("MainWindow", "溫度數據監控"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())